version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
